export type RiskFlag = 'None' | 'Minor' | 'Watch' | 'High';
export type AllocationStatus = 'Active' | 'Bench' | 'Overloaded';
export type TsCompliance =
  | 'Compliant'
  | 'Minor Late'
  | 'Late'
  | 'Non-Compliant'
  | 'Unapproved Absence'
  | 'Late Pattern';
export type Tier =
  | 'Exceeds Expectations'
  | 'Meets Expectations'
  | 'Partially Meets'
  | 'Does Not Meet';

export interface Employee {
  id: string;
  role: string;
  dept: string;
  level: string;
  status: string;
  tier: Tier;
  account: string;
  avg_score: number;
  score_t3: number;
  score_t4: number;
  classification: string;
  ts_compliance: TsCompliance;
  ot_t4: number;
  risk_flag: RiskFlag;
  open_violations: number;
  allocation_status: AllocationStatus;
  readiness: number;
  risk_note: string;
  feedback: string;
  feedback_prev: string;
}

export const ACCOUNTS: Record<string, string> = {
  'ACC-A': 'Account Alpha',
  'ACC-B': 'Account Beta',
  'ACC-C': 'Account Gamma',
  'ACC-D': 'Account Delta',
  'ACC-E': 'Account Epsilon',
  INTERNAL: 'Internal',
};

export const SCORE_THRESHOLDS = {
  excellent: 4.5,
  good: 3.5,
  watch: 2.8,
} as const;

export const SELF_ID = 'EMP-001';

export const EMPLOYEES: Employee[] = [
  {
    id: 'EMP-001',
    role: 'Senior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L4',
    status: 'Active',
    tier: 'Exceeds Expectations',
    account: 'ACC-C',
    avg_score: 4.47,
    score_t3: 4.52,
    score_t4: 4.42,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 8.0,
    risk_flag: 'Minor',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.86,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-002',
    role: 'Junior QA Engineer',
    dept: 'IT - QA',
    level: 'L2',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-D',
    avg_score: 3.83,
    score_t3: 3.81,
    score_t4: 3.85,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 8.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.55,
    risk_note: 'No flags',
    feedback: 'Consistent delivery and accountability',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-003',
    role: 'Engineering Manager',
    dept: 'IT - Engineering',
    level: 'L6',
    status: 'Active',
    tier: 'Exceeds Expectations',
    account: 'ACC-B',
    avg_score: 4.93,
    score_t3: 4.9,
    score_t4: 4.95,
    classification: 'Excellent',
    ts_compliance: 'Compliant',
    ot_t4: 6.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.92,
    risk_note: 'Top Performer',
    feedback: 'Strong leadership and coordination',
    feedback_prev: 'High learning agility and initiative',
  },
  {
    id: 'EMP-004',
    role: 'QA Lead',
    dept: 'IT - QA',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 1.7,
    score_t3: 1.8,
    score_t4: 1.6,
    classification: 'Below Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 4.0,
    risk_flag: 'High',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.55,
    risk_note: 'Low KPI (<2.5); High-Risk Violation',
    feedback: 'Performance improvement discussion initiated',
    feedback_prev: 'Needs additional coaching and support',
  },
  {
    id: 'EMP-005',
    role: 'Senior Project Manager',
    dept: 'IT - PM',
    level: 'L6',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-E',
    avg_score: 4.0,
    score_t3: 3.96,
    score_t4: 4.04,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 6.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.67,
    risk_note: 'No flags',
    feedback: 'Good client management and issue resolution',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-006',
    role: 'Senior DevOps Engineer',
    dept: 'IT - DevOps',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-D',
    avg_score: 3.61,
    score_t3: 3.69,
    score_t4: 3.53,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'High',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.51,
    risk_note: 'High-Risk Violation',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Good client management and issue resolution',
  },
  {
    id: 'EMP-007',
    role: 'QA Engineer',
    dept: 'IT - QA',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-C',
    avg_score: 3.34,
    score_t3: 3.32,
    score_t4: 3.36,
    classification: 'Meets Expectations',
    ts_compliance: 'Unapproved Absence',
    ot_t4: 2.0,
    risk_flag: 'High',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.56,
    risk_note: 'High-Risk Violation; Absence Violation',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-008',
    role: 'Junior QA Engineer',
    dept: 'IT - QA',
    level: 'L1',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'ACC-E',
    avg_score: 2.13,
    score_t3: 2.22,
    score_t4: 2.05,
    classification: 'Below Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 8.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.29,
    risk_note: 'Low KPI (<2.5)',
    feedback: 'Needs additional coaching and support',
    feedback_prev: 'Needs additional coaching and support',
  },
  {
    id: 'EMP-009',
    role: 'Senior QA Engineer',
    dept: 'IT - QA',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'Internal',
    avg_score: 3.76,
    score_t3: 3.85,
    score_t4: 3.67,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Bench',
    readiness: 0.63,
    risk_note: 'Benched',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-010',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L1',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-D',
    avg_score: 3.67,
    score_t3: 3.59,
    score_t4: 3.74,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.65,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-011',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L1',
    status: 'Active',
    tier: 'Exceeds Expectations',
    account: 'ACC-A',
    avg_score: 4.82,
    score_t3: 4.8,
    score_t4: 4.85,
    classification: 'Excellent',
    ts_compliance: 'Compliant',
    ot_t4: 4.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.95,
    risk_note: 'Top Performer',
    feedback: 'Strong collaboration and team support',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-012',
    role: 'DevOps Engineer',
    dept: 'IT - DevOps',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-C',
    avg_score: 2.0,
    score_t3: 2.1,
    score_t4: 1.9,
    classification: 'Below Expectations',
    ts_compliance: 'Late Pattern',
    ot_t4: 0.0,
    risk_flag: 'High',
    open_violations: 3,
    allocation_status: 'Active',
    readiness: 0.54,
    risk_note: 'Low KPI (<2.5); Multiple Open Violations; Lateness Pattern',
    feedback: 'Needs additional coaching and support',
    feedback_prev: 'Performance improvement discussion initiated',
  },
  {
    id: 'EMP-013',
    role: 'Tech Lead',
    dept: 'IT - Engineering',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.05,
    score_t3: 3.1,
    score_t4: 3.01,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 6.0,
    risk_flag: 'Watch',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.51,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-014',
    role: 'Software Engineer',
    dept: 'IT - Engineering',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-C',
    avg_score: 3.96,
    score_t3: 4.01,
    score_t4: 3.9,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 15.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Overloaded',
    readiness: 0.55,
    risk_note: 'No flags',
    feedback: 'Consistent delivery and accountability',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-015',
    role: 'Junior QA Engineer',
    dept: 'IT - QA',
    level: 'L2',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-A',
    avg_score: 3.48,
    score_t3: 3.54,
    score_t4: 3.42,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 8.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.61,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-016',
    role: 'Senior DevOps Engineer',
    dept: 'IT - DevOps',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-E',
    avg_score: 3.46,
    score_t3: 3.39,
    score_t4: 3.54,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 10.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.54,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-017',
    role: 'Senior Business Analyst',
    dept: 'IT - BA',
    level: 'L4',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'Internal',
    avg_score: 3.01,
    score_t3: 2.96,
    score_t4: 3.06,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 2.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Bench',
    readiness: 0.47,
    risk_note: 'Benched',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-018',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L1',
    status: 'Resigned',
    tier: 'Meets Expectations',
    account: 'ACC-A',
    avg_score: 4.11,
    score_t3: 4.14,
    score_t4: 4.08,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 10.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.61,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-019',
    role: 'QA Engineer',
    dept: 'IT - QA',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-D',
    avg_score: 3.97,
    score_t3: 3.9,
    score_t4: 4.04,
    classification: 'Good',
    ts_compliance: 'Unapproved Absence',
    ot_t4: 2.0,
    risk_flag: 'Watch',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.51,
    risk_note: 'Absence Violation',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-020',
    role: 'Junior QA Engineer',
    dept: 'IT - QA',
    level: 'L1',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-D',
    avg_score: 3.6,
    score_t3: 3.58,
    score_t4: 3.62,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.53,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-021',
    role: 'Senior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-D',
    avg_score: 3.87,
    score_t3: 3.86,
    score_t4: 3.87,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.56,
    risk_note: 'No flags',
    feedback: 'Consistent delivery and accountability',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-022',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L2',
    status: 'PIP',
    tier: 'Does Not Meet',
    account: 'Internal',
    avg_score: 1.27,
    score_t3: 1.21,
    score_t4: 1.32,
    classification: 'Poor',
    ts_compliance: 'Compliant',
    ot_t4: 6.0,
    risk_flag: 'Watch',
    open_violations: 0,
    allocation_status: 'Bench',
    readiness: 0.09,
    risk_note: 'Low KPI (<2.5); Benched',
    feedback: 'Significant gaps in delivery and quality',
    feedback_prev: 'Significant gaps in delivery and quality',
  },
  {
    id: 'EMP-023',
    role: 'Delivery Manager',
    dept: 'IT - Delivery',
    level: 'L7',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.97,
    score_t3: 3.98,
    score_t4: 3.96,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 2.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.69,
    risk_note: 'No flags',
    feedback: 'Good client management and issue resolution',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-024',
    role: 'Tech Lead',
    dept: 'IT - Engineering',
    level: 'L5',
    status: 'Active',
    tier: 'Exceeds Expectations',
    account: 'ACC-C',
    avg_score: 4.72,
    score_t3: 4.7,
    score_t4: 4.75,
    classification: 'Excellent',
    ts_compliance: 'Compliant',
    ot_t4: 8.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.79,
    risk_note: 'Top Performer',
    feedback: 'High learning agility and initiative',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-025',
    role: 'QA Engineer',
    dept: 'IT - QA',
    level: 'L3',
    status: 'Resigned',
    tier: 'Partially Meets',
    account: 'ACC-A',
    avg_score: 2.14,
    score_t3: 2.21,
    score_t4: 2.07,
    classification: 'Below Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 2.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.33,
    risk_note: 'Low KPI (<2.5)',
    feedback: 'Performance improvement discussion initiated',
    feedback_prev: 'Performance improvement discussion initiated',
  },
  {
    id: 'EMP-026',
    role: 'DevOps Engineer',
    dept: 'IT - DevOps',
    level: 'L3',
    status: 'Active',
    tier: 'Does Not Meet',
    account: 'ACC-A',
    avg_score: 1.85,
    score_t3: 1.85,
    score_t4: 1.85,
    classification: 'Below Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 4.0,
    risk_flag: 'High',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.08,
    risk_note: 'Low KPI (<2.5); High-Risk Violation',
    feedback: 'Performance improvement discussion initiated',
    feedback_prev: 'Needs additional coaching and support',
  },
  {
    id: 'EMP-027',
    role: 'Senior Project Manager',
    dept: 'IT - PM',
    level: 'L6',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-E',
    avg_score: 3.58,
    score_t3: 3.63,
    score_t4: 3.53,
    classification: 'Good',
    ts_compliance: 'Late Pattern',
    ot_t4: 6.0,
    risk_flag: 'High',
    open_violations: 2,
    allocation_status: 'Active',
    readiness: 0.52,
    risk_note: 'High-Risk Violation; Lateness Pattern',
    feedback: 'Meets expectations',
    feedback_prev: 'Good client management and issue resolution',
  },
  {
    id: 'EMP-028',
    role: 'Senior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L4',
    status: 'PIP',
    tier: 'Does Not Meet',
    account: 'ACC-A',
    avg_score: 1.52,
    score_t3: 1.45,
    score_t4: 1.58,
    classification: 'Below Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Overloaded',
    readiness: 0.13,
    risk_note: 'Low KPI (<2.5)',
    feedback: 'Performance improvement discussion initiated',
    feedback_prev: 'Significant gaps in delivery and quality',
  },
  {
    id: 'EMP-029',
    role: 'Senior Project Manager',
    dept: 'IT - PM',
    level: 'L6',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'Internal',
    avg_score: 3.96,
    score_t3: 4.0,
    score_t4: 3.91,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 6.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Bench',
    readiness: 0.71,
    risk_note: 'Benched',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-030',
    role: 'Tech Lead',
    dept: 'IT - Engineering',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'Internal',
    avg_score: 4.41,
    score_t3: 4.36,
    score_t4: 4.45,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 8.0,
    risk_flag: 'High',
    open_violations: 0,
    allocation_status: 'Bench',
    readiness: 0.63,
    risk_note: 'High-Risk Violation; Benched',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-031',
    role: 'Senior DevOps Engineer',
    dept: 'IT - DevOps',
    level: 'L4',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'ACC-B',
    avg_score: 2.25,
    score_t3: 2.3,
    score_t4: 2.2,
    classification: 'Below Expectations',
    ts_compliance: 'Unapproved Absence',
    ot_t4: 0.0,
    risk_flag: 'High',
    open_violations: 4,
    allocation_status: 'Active',
    readiness: 0.49,
    risk_note: 'Low KPI (<2.5); Multiple Open Violations; Absence Violation',
    feedback: 'Needs additional coaching and support',
    feedback_prev: 'Performance improvement discussion initiated',
  },
  {
    id: 'EMP-032',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L1',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-E',
    avg_score: 3.82,
    score_t3: 3.8,
    score_t4: 3.84,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 6.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.66,
    risk_note: 'No flags',
    feedback: 'Consistent delivery and accountability',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-033',
    role: 'Business Dev Executive',
    dept: 'Admin - Sales',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.56,
    score_t3: 3.62,
    score_t4: 3.51,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'Watch',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.67,
    risk_note: 'No flags',
    feedback: 'Consistent delivery and accountability',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-034',
    role: 'Business Analyst',
    dept: 'IT - BA',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-E',
    avg_score: 3.59,
    score_t3: 3.64,
    score_t4: 3.55,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 6.0,
    risk_flag: 'Watch',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.65,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-035',
    role: 'HR Executive',
    dept: 'Admin - HR',
    level: 'L2',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-A',
    avg_score: 3.77,
    score_t3: 3.82,
    score_t4: 3.72,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 2.0,
    risk_flag: 'Watch',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.52,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-036',
    role: 'Senior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-A',
    avg_score: 3.84,
    score_t3: 3.81,
    score_t4: 3.87,
    classification: 'Good',
    ts_compliance: 'Late Pattern',
    ot_t4: 8.0,
    risk_flag: 'High',
    open_violations: 4,
    allocation_status: 'Active',
    readiness: 0.64,
    risk_note: 'Multiple Open Violations; Lateness Pattern',
    feedback: 'Good client management and issue resolution',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-037',
    role: 'Senior Business Analyst',
    dept: 'IT - BA',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-C',
    avg_score: 3.19,
    score_t3: 3.15,
    score_t4: 3.22,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 4.0,
    risk_flag: 'High',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.56,
    risk_note: 'High-Risk Violation',
    feedback: 'Meets expectations',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-038',
    role: 'Principal Engineer',
    dept: 'IT - Engineering',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.3,
    score_t3: 3.24,
    score_t4: 3.36,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'High',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.71,
    risk_note: 'High-Risk Violation',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-039',
    role: 'Tech Lead',
    dept: 'IT - Engineering',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-C',
    avg_score: 3.14,
    score_t3: 3.21,
    score_t4: 3.07,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'High',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.58,
    risk_note: 'High-Risk Violation',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-040',
    role: 'Senior QA Engineer',
    dept: 'IT - QA',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.27,
    score_t3: 3.28,
    score_t4: 3.26,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 6.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.7,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-041',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L1',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'ACC-A',
    avg_score: 3.18,
    score_t3: 3.09,
    score_t4: 3.28,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 8.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.35,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-042',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L2',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'ACC-C',
    avg_score: 2.88,
    score_t3: 2.94,
    score_t4: 2.83,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 4.0,
    risk_flag: 'Minor',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.49,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-043',
    role: 'Project Manager',
    dept: 'IT - PM',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'Internal',
    avg_score: 3.4,
    score_t3: 3.3,
    score_t4: 3.49,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 2.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Bench',
    readiness: 0.61,
    risk_note: 'Benched',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-044',
    role: 'Junior QA Engineer',
    dept: 'IT - QA',
    level: 'L1',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-A',
    avg_score: 3.1,
    score_t3: 3.17,
    score_t4: 3.03,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.73,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-045',
    role: 'Senior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L4',
    status: 'Active',
    tier: 'Exceeds Expectations',
    account: 'ACC-D',
    avg_score: 5.0,
    score_t3: 5.0,
    score_t4: 5.0,
    classification: 'Excellent',
    ts_compliance: 'Late Pattern',
    ot_t4: 4.0,
    risk_flag: 'High',
    open_violations: 4,
    allocation_status: 'Active',
    readiness: 0.84,
    risk_note: 'Top Performer; Multiple Open Violations; Lateness Pattern',
    feedback: 'Strong leadership and coordination',
    feedback_prev: 'Proactive and self-motivated',
  },
  {
    id: 'EMP-046',
    role: 'Senior QA Engineer',
    dept: 'IT - QA',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-E',
    avg_score: 3.83,
    score_t3: 3.83,
    score_t4: 3.83,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 2.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.6,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-047',
    role: 'Accountant',
    dept: 'Admin - Finance',
    level: 'L2',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-A',
    avg_score: 3.95,
    score_t3: 3.88,
    score_t4: 4.02,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 2.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Overloaded',
    readiness: 0.59,
    risk_note: 'No flags',
    feedback: 'Consistent delivery and accountability',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-048',
    role: 'Senior Project Manager',
    dept: 'IT - PM',
    level: 'L6',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-A',
    avg_score: 3.99,
    score_t3: 4.01,
    score_t4: 3.97,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'Watch',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.73,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-049',
    role: 'Senior DevOps Engineer',
    dept: 'IT - DevOps',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.7,
    score_t3: 3.67,
    score_t4: 3.73,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.68,
    risk_note: 'No flags',
    feedback: 'Good client management and issue resolution',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-050',
    role: 'Junior QA Engineer',
    dept: 'IT - QA',
    level: 'L2',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'ACC-A',
    avg_score: 2.57,
    score_t3: 2.62,
    score_t4: 2.52,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 6.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Overloaded',
    readiness: 0.32,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-051',
    role: 'Delivery Manager',
    dept: 'IT - Delivery',
    level: 'L7',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'Internal',
    avg_score: 3.89,
    score_t3: 3.9,
    score_t4: 3.88,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 8.0,
    risk_flag: 'Watch',
    open_violations: 2,
    allocation_status: 'Bench',
    readiness: 0.61,
    risk_note: 'Benched',
    feedback: 'Consistent delivery and accountability',
    feedback_prev: 'Good client management and issue resolution',
  },
  {
    id: 'EMP-052',
    role: 'Software Engineer',
    dept: 'IT - Engineering',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.99,
    score_t3: 4.07,
    score_t4: 3.9,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Overloaded',
    readiness: 0.63,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-053',
    role: 'Business Dev Executive',
    dept: 'Admin - Sales',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 4.04,
    score_t3: 3.96,
    score_t4: 4.11,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 6.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.67,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Good client management and issue resolution',
  },
  {
    id: 'EMP-054',
    role: 'Junior QA Engineer',
    dept: 'IT - QA',
    level: 'L2',
    status: 'Resigned',
    tier: 'Exceeds Expectations',
    account: 'ACC-A',
    avg_score: 4.13,
    score_t3: 4.07,
    score_t4: 4.2,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 10.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.86,
    risk_note: 'No flags',
    feedback: 'Good client management and issue resolution',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-055',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L2',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.19,
    score_t3: 3.1,
    score_t4: 3.27,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 2.0,
    risk_flag: 'High',
    open_violations: 2,
    allocation_status: 'Active',
    readiness: 0.51,
    risk_note: 'High-Risk Violation',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-056',
    role: 'Project Manager',
    dept: 'IT - PM',
    level: 'L5',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'ACC-D',
    avg_score: 2.91,
    score_t3: 2.86,
    score_t4: 2.96,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 2.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.27,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-057',
    role: 'QA Engineer',
    dept: 'IT - QA',
    level: 'L3',
    status: 'Resigned',
    tier: 'Partially Meets',
    account: 'ACC-D',
    avg_score: 3.02,
    score_t3: 2.97,
    score_t4: 3.06,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 6.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.32,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-058',
    role: 'Senior Business Analyst',
    dept: 'IT - BA',
    level: 'L4',
    status: 'Active',
    tier: 'Exceeds Expectations',
    account: 'ACC-B',
    avg_score: 4.38,
    score_t3: 4.3,
    score_t4: 4.46,
    classification: 'Good',
    ts_compliance: 'Late Pattern',
    ot_t4: 4.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.75,
    risk_note: 'Lateness Pattern',
    feedback: 'Consistent delivery and accountability',
    feedback_prev: 'Good client management and issue resolution',
  },
  {
    id: 'EMP-059',
    role: 'Admin Executive',
    dept: 'Admin - GA',
    level: 'L2',
    status: 'Active',
    tier: 'Exceeds Expectations',
    account: 'ACC-A',
    avg_score: 4.39,
    score_t3: 4.48,
    score_t4: 4.3,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 2.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.8,
    risk_note: 'No flags',
    feedback: 'Good client management and issue resolution',
    feedback_prev: 'Good client management and issue resolution',
  },
  {
    id: 'EMP-060',
    role: 'Senior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-C',
    avg_score: 3.91,
    score_t3: 3.98,
    score_t4: 3.84,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 15.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.72,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Good client management and issue resolution',
  },
  {
    id: 'EMP-061',
    role: 'QA Engineer',
    dept: 'IT - QA',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-D',
    avg_score: 3.96,
    score_t3: 4.04,
    score_t4: 3.87,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 2.0,
    risk_flag: 'High',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.68,
    risk_note: 'High-Risk Violation',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-062',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L2',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'Internal',
    avg_score: 3.69,
    score_t3: 3.7,
    score_t4: 3.67,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'High',
    open_violations: 3,
    allocation_status: 'Bench',
    readiness: 0.74,
    risk_note: 'Multiple Open Violations; Benched',
    feedback: 'Consistent delivery and accountability',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-063',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L1',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'ACC-C',
    avg_score: 2.4,
    score_t3: 2.32,
    score_t4: 2.48,
    classification: 'Below Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Overloaded',
    readiness: 0.42,
    risk_note: 'Low KPI (<2.5)',
    feedback: 'Performance improvement discussion initiated',
    feedback_prev: 'Performance improvement discussion initiated',
  },
  {
    id: 'EMP-064',
    role: 'Senior QA Engineer',
    dept: 'IT - QA',
    level: 'L4',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'ACC-B',
    avg_score: 3.05,
    score_t3: 3.0,
    score_t4: 3.11,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 6.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.25,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-065',
    role: 'QA Engineer',
    dept: 'IT - QA',
    level: 'L3',
    status: 'Active',
    tier: 'Exceeds Expectations',
    account: 'ACC-C',
    avg_score: 4.73,
    score_t3: 4.66,
    score_t4: 4.81,
    classification: 'Excellent',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'Watch',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.93,
    risk_note: 'Top Performer',
    feedback: 'High learning agility and initiative',
    feedback_prev: 'High learning agility and initiative',
  },
  {
    id: 'EMP-066',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L2',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-C',
    avg_score: 3.76,
    score_t3: 3.71,
    score_t4: 3.82,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 2.0,
    risk_flag: 'High',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.53,
    risk_note: 'High-Risk Violation',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Good client management and issue resolution',
  },
  {
    id: 'EMP-067',
    role: 'Engineering Manager',
    dept: 'IT - Engineering',
    level: 'L6',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-E',
    avg_score: 3.33,
    score_t3: 3.36,
    score_t4: 3.31,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 2.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.72,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-068',
    role: 'Principal Engineer',
    dept: 'IT - Engineering',
    level: 'L5',
    status: 'PIP',
    tier: 'Does Not Meet',
    account: 'ACC-B',
    avg_score: 1.2,
    score_t3: 1.23,
    score_t4: 1.17,
    classification: 'Poor',
    ts_compliance: 'Minor Late',
    ot_t4: 6.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.08,
    risk_note: 'Low KPI (<2.5)',
    feedback: 'Performance improvement plan required',
    feedback_prev: 'Significant gaps in delivery and quality',
  },
  {
    id: 'EMP-069',
    role: 'Finance Manager',
    dept: 'Admin - Finance',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-D',
    avg_score: 3.59,
    score_t3: 3.61,
    score_t4: 3.57,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 2.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.51,
    risk_note: 'No flags',
    feedback: 'Good client management and issue resolution',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-070',
    role: 'Software Engineer',
    dept: 'IT - Engineering',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'Internal',
    avg_score: 3.55,
    score_t3: 3.58,
    score_t4: 3.52,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 2.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Bench',
    readiness: 0.7,
    risk_note: 'Benched',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Good client management and issue resolution',
  },
  {
    id: 'EMP-071',
    role: 'Senior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.93,
    score_t3: 3.86,
    score_t4: 4.01,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.52,
    risk_note: 'No flags',
    feedback: 'Good client management and issue resolution',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-072',
    role: 'Software Engineer',
    dept: 'IT - Engineering',
    level: 'L3',
    status: 'Resigned',
    tier: 'Meets Expectations',
    account: 'ACC-A',
    avg_score: 3.46,
    score_t3: 3.55,
    score_t4: 3.37,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.55,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Good client management and issue resolution',
  },
  {
    id: 'EMP-073',
    role: 'Junior QA Engineer',
    dept: 'IT - QA',
    level: 'L2',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.62,
    score_t3: 3.64,
    score_t4: 3.61,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 4.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.53,
    risk_note: 'No flags',
    feedback: 'Consistent delivery and accountability',
    feedback_prev: 'Good client management and issue resolution',
  },
  {
    id: 'EMP-074',
    role: 'Principal Engineer',
    dept: 'IT - Engineering',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-C',
    avg_score: 4.19,
    score_t3: 4.24,
    score_t4: 4.14,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.53,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-075',
    role: 'HR Manager',
    dept: 'Admin - HR',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-D',
    avg_score: 3.48,
    score_t3: 3.51,
    score_t4: 3.46,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 6.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.64,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-076',
    role: 'Senior DevOps Engineer',
    dept: 'IT - DevOps',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.62,
    score_t3: 3.57,
    score_t4: 3.66,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 4.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.67,
    risk_note: 'No flags',
    feedback: 'Good client management and issue resolution',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-077',
    role: 'Tech Lead',
    dept: 'IT - Engineering',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-A',
    avg_score: 3.35,
    score_t3: 3.39,
    score_t4: 3.32,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'Watch',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.65,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-078',
    role: 'Senior Project Manager',
    dept: 'IT - PM',
    level: 'L6',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-A',
    avg_score: 3.16,
    score_t3: 3.12,
    score_t4: 3.19,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 4.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.72,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-079',
    role: 'Software Engineer',
    dept: 'IT - Engineering',
    level: 'L3',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'ACC-D',
    avg_score: 2.2,
    score_t3: 2.24,
    score_t4: 2.16,
    classification: 'Below Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 2.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.45,
    risk_note: 'Low KPI (<2.5)',
    feedback: 'Performance improvement discussion initiated',
    feedback_prev: 'Performance improvement discussion initiated',
  },
  {
    id: 'EMP-080',
    role: 'Senior Project Manager',
    dept: 'IT - PM',
    level: 'L6',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.76,
    score_t3: 3.77,
    score_t4: 3.76,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.7,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Good client management and issue resolution',
  },
  {
    id: 'EMP-081',
    role: 'QA Lead',
    dept: 'IT - QA',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-E',
    avg_score: 3.74,
    score_t3: 3.71,
    score_t4: 3.77,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 4.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Overloaded',
    readiness: 0.7,
    risk_note: 'No flags',
    feedback: 'Good client management and issue resolution',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-082',
    role: 'Business Analyst',
    dept: 'IT - BA',
    level: 'L3',
    status: 'PIP',
    tier: 'Does Not Meet',
    account: 'ACC-C',
    avg_score: 1.32,
    score_t3: 1.4,
    score_t4: 1.24,
    classification: 'Poor',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.13,
    risk_note: 'Low KPI (<2.5)',
    feedback: 'Performance improvement plan required',
    feedback_prev: 'Significant gaps in delivery and quality',
  },
  {
    id: 'EMP-083',
    role: 'Senior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-C',
    avg_score: 3.56,
    score_t3: 3.63,
    score_t4: 3.49,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Overloaded',
    readiness: 0.68,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-084',
    role: 'Delivery Manager',
    dept: 'IT - Delivery',
    level: 'L7',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.68,
    score_t3: 3.69,
    score_t4: 3.67,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.61,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent delivery and accountability',
  },
  {
    id: 'EMP-085',
    role: 'DevOps Engineer',
    dept: 'IT - DevOps',
    level: 'L3',
    status: 'Active',
    tier: 'Does Not Meet',
    account: 'Internal',
    avg_score: 1.63,
    score_t3: 1.7,
    score_t4: 1.56,
    classification: 'Below Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 4.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Bench',
    readiness: 0.07,
    risk_note: 'Low KPI (<2.5); Benched',
    feedback: 'Performance improvement discussion initiated',
    feedback_prev: 'Performance improvement discussion initiated',
  },
  {
    id: 'EMP-086',
    role: 'Senior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L4',
    status: 'Active',
    tier: 'Exceeds Expectations',
    account: 'ACC-A',
    avg_score: 4.9,
    score_t3: 4.97,
    score_t4: 4.84,
    classification: 'Excellent',
    ts_compliance: 'Compliant',
    ot_t4: 2.0,
    risk_flag: 'High',
    open_violations: 4,
    allocation_status: 'Active',
    readiness: 0.79,
    risk_note: 'Top Performer; Multiple Open Violations',
    feedback: 'High-quality output and completeness',
    feedback_prev: 'High learning agility and initiative',
  },
  {
    id: 'EMP-087',
    role: 'Senior Project Manager',
    dept: 'IT - PM',
    level: 'L6',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'ACC-C',
    avg_score: 2.17,
    score_t3: 2.08,
    score_t4: 2.25,
    classification: 'Below Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Overloaded',
    readiness: 0.46,
    risk_note: 'Low KPI (<2.5)',
    feedback: 'Performance improvement discussion initiated',
    feedback_prev: 'Performance improvement discussion initiated',
  },
  {
    id: 'EMP-088',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L2',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-C',
    avg_score: 3.51,
    score_t3: 3.48,
    score_t4: 3.55,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.68,
    risk_note: 'No flags',
    feedback: 'Good client management and issue resolution',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-089',
    role: 'Principal Engineer',
    dept: 'IT - Engineering',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-D',
    avg_score: 3.73,
    score_t3: 3.67,
    score_t4: 3.8,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 8.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.73,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-090',
    role: 'Senior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L4',
    status: 'Resigned',
    tier: 'Exceeds Expectations',
    account: 'ACC-C',
    avg_score: 4.44,
    score_t3: 4.45,
    score_t4: 4.43,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 8.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.87,
    risk_note: 'No flags',
    feedback: 'Meets expectations',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-091',
    role: 'Finance Manager',
    dept: 'Admin - Finance',
    level: 'L5',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'ACC-D',
    avg_score: 2.79,
    score_t3: 2.76,
    score_t4: 2.81,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'High',
    open_violations: 2,
    allocation_status: 'Active',
    readiness: 0.46,
    risk_note: 'High-Risk Violation',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-092',
    role: 'Senior QA Engineer',
    dept: 'IT - QA',
    level: 'L4',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-A',
    avg_score: 3.09,
    score_t3: 3.15,
    score_t4: 3.04,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 10.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Overloaded',
    readiness: 0.73,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-093',
    role: 'BD Manager',
    dept: 'Admin - Sales',
    level: 'L6',
    status: 'Active',
    tier: 'Exceeds Expectations',
    account: 'ACC-D',
    avg_score: 4.93,
    score_t3: 5.0,
    score_t4: 4.86,
    classification: 'Excellent',
    ts_compliance: 'Compliant',
    ot_t4: 4.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.86,
    risk_note: 'Top Performer',
    feedback: 'High learning agility and initiative',
    feedback_prev: 'Strong leadership and coordination',
  },
  {
    id: 'EMP-094',
    role: 'Senior Project Manager',
    dept: 'IT - PM',
    level: 'L6',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-E',
    avg_score: 3.33,
    score_t3: 3.42,
    score_t4: 3.25,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 2.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.62,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-095',
    role: 'Business Analyst',
    dept: 'IT - BA',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-E',
    avg_score: 3.74,
    score_t3: 3.83,
    score_t4: 3.65,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 4.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.51,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-096',
    role: 'Junior Software Engineer',
    dept: 'IT - Engineering',
    level: 'L2',
    status: 'Active',
    tier: 'Partially Meets',
    account: 'ACC-B',
    avg_score: 2.91,
    score_t3: 2.84,
    score_t4: 2.98,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 4.0,
    risk_flag: 'Watch',
    open_violations: 1,
    allocation_status: 'Active',
    readiness: 0.35,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-097',
    role: 'QA Engineer',
    dept: 'IT - QA',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-A',
    avg_score: 3.16,
    score_t3: 3.2,
    score_t4: 3.12,
    classification: 'Meets Expectations',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'Minor',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.67,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-098',
    role: 'QA Engineer',
    dept: 'IT - QA',
    level: 'L3',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-B',
    avg_score: 3.62,
    score_t3: 3.62,
    score_t4: 3.62,
    classification: 'Good',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Overloaded',
    readiness: 0.61,
    risk_note: 'No flags',
    feedback: 'Good client management and issue resolution',
    feedback_prev: 'Meets expectations',
  },
  {
    id: 'EMP-099',
    role: 'Principal Engineer',
    dept: 'IT - Engineering',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-D',
    avg_score: 3.35,
    score_t3: 3.39,
    score_t4: 3.32,
    classification: 'Meets Expectations',
    ts_compliance: 'Compliant',
    ot_t4: 0.0,
    risk_flag: 'Watch',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.74,
    risk_note: 'No flags',
    feedback: 'Consistent performance maintained',
    feedback_prev: 'Consistent performance maintained',
  },
  {
    id: 'EMP-100',
    role: 'QA Lead',
    dept: 'IT - QA',
    level: 'L5',
    status: 'Active',
    tier: 'Meets Expectations',
    account: 'ACC-E',
    avg_score: 3.9,
    score_t3: 3.8,
    score_t4: 3.99,
    classification: 'Good',
    ts_compliance: 'Minor Late',
    ot_t4: 0.0,
    risk_flag: 'None',
    open_violations: 0,
    allocation_status: 'Active',
    readiness: 0.53,
    risk_note: 'No flags',
    feedback: 'Consistent delivery and accountability',
    feedback_prev: 'Meets expectations',
  },
];
