// Verbatim reference data transcribed from ELC_05_Employee_Performance_Tracking.xlsx.
// These three datasets are fixed lookups the ARIA agent's rule engine depends on, so
// they are seeded exactly as documented (DS-07, DS-04b, REF) rather than generated.

/** DS-07 · Performance NORM / Rule-based Standards — the full 27-rule set. */
export const NORM_RULES = [
  [
    'NORM-P01',
    'KPI Score',
    'Monthly performance score — Excellent',
    '>= 4.5',
    'Excellent',
    'Highlight in report; eligible for outstanding recognition',
    'High',
    'All employees',
  ],
  [
    'NORM-P02',
    'KPI Score',
    'Monthly performance score — Good',
    '3.5 – 4.49',
    'Good',
    'No action required; standard recognition',
    'Medium',
    'All employees',
  ],
  [
    'NORM-P03',
    'KPI Score',
    'Monthly performance score — Meets Expectations',
    '2.5 – 3.49',
    'Meets Expectations',
    'Monitor next cycle; optional coaching',
    'Medium',
    'All employees',
  ],
  [
    'NORM-P04',
    'KPI Score',
    'Monthly performance score — Below Expectations',
    '1.5 – 2.49',
    'Below Expectations',
    'Trigger PIP discussion with manager; flag to HR',
    'High',
    'All employees',
  ],
  [
    'NORM-P05',
    'KPI Score',
    'Monthly performance score — Unsatisfactory',
    '< 1.5',
    'Unsatisfactory',
    'Escalate to HR Director; formal performance review required',
    'Critical',
    'All employees',
  ],
  [
    'NORM-P06',
    'KPI Score',
    'Consecutive below-expectations rating (2 cycles)',
    'Score < 2.5 for 2 consecutive months',
    'At Risk',
    'Mandatory PIP initiated; HR and direct manager notified',
    'Critical',
    'All employees',
  ],
  [
    'NORM-T01',
    'Timesheet',
    'Full attendance — no absence or late',
    'absent_days=0 AND late_days=0',
    'Compliant',
    'Standard — no action',
    'Low',
    'All employees',
  ],
  [
    'NORM-T02',
    'Timesheet',
    'Late arrival threshold',
    'late_days >= 3 in a month',
    'Lateness Pattern',
    'Verbal warning issued; flag to manager',
    'Medium',
    'All employees',
  ],
  [
    'NORM-T03',
    'Timesheet',
    'Unapproved absence threshold',
    'absent_unapproved_days >= 1',
    'Absence Violation',
    'Written warning; escalate if repeated next month',
    'High',
    'All employees',
  ],
  [
    'NORM-T04',
    'Timesheet',
    'Overloaded OT flag',
    'total_ot_hours > 40 in a month',
    'OT Overload',
    'HR to verify workload; check resource allocation balance',
    'Medium',
    'All employees',
  ],
  [
    'NORM-T05',
    'Timesheet',
    'Low actual work days vs expected',
    'actual_work_days < 0.9 * work_days_in_month AND no leave approved',
    'Attendance Gap',
    'Flag to HR; request explanation from employee',
    'High',
    'All employees',
  ],
  [
    'NORM-R01',
    'Resource Allocation',
    'Over-allocated employee',
    'sum(allocation_pct) > 1.2 (120%)',
    'Overloaded',
    'Alert to manager; review task redistribution within 1 week',
    'High',
    'All employees',
  ],
  [
    'NORM-R02',
    'Resource Allocation',
    'Benched employee exceeding idle threshold',
    'assignment_type = Bench AND bench_duration > 30 days',
    'Bench Risk',
    'Escalate to DM; assign to internal project or training',
    'Medium',
    'All employees',
  ],
  [
    'NORM-R03',
    'Resource Allocation',
    'Multi-project employee — performance monitoring required',
    'work_on_other = Yes AND allocation_pct < 0.5 on main account',
    'Split Focus',
    'Flag for manager review; validate KPI context',
    'Low',
    'All employees',
  ],
  [
    'NORM-V01',
    'Violation',
    'Critical violation — immediate escalation required',
    'severity = Critical',
    'Critical Risk',
    'Suspend pending investigation; notify HR Director + Legal',
    'Critical',
    'All employees',
  ],
  [
    'NORM-V02',
    'Violation',
    'High severity violation',
    'severity = High',
    'High Risk',
    'Final warning / PIP initiated; notify HR within 48h',
    'High',
    'All employees',
  ],
  [
    'NORM-V03',
    'Violation',
    'Medium severity violation',
    'severity = Medium',
    'Medium Risk',
    'Written warning issued; document in HR record',
    'Medium',
    'All employees',
  ],
  [
    'NORM-V04',
    'Violation',
    'Low severity violation',
    'severity = Low',
    'Minor',
    'Verbal warning; manager reminder',
    'Low',
    'All employees',
  ],
  [
    'NORM-V05',
    'Violation',
    'Multiple open violations',
    'open_cases >= 3',
    'Escalation Required',
    'Automatic escalation to HR Director; PIP or exit review',
    'Critical',
    'All employees',
  ],
  [
    'NORM-V06',
    'Violation',
    'Repeated same violation category (2+ times)',
    'same category violation_count >= 2',
    'Repeat Offender',
    'Upgrade severity by one level; mandatory HR review',
    'High',
    'All employees',
  ],
  [
    'NORM-C01',
    'Composite Risk',
    'Low KPI + Violation in same review period',
    'Score < 2.5 AND has_violation = True',
    'Dual Risk Flag',
    'Combined HR and manager review required within 5 business days',
    'Critical',
    'All employees',
  ],
  [
    'NORM-C02',
    'Composite Risk',
    'High performer with violation — context required',
    'Score >= 4.5 AND has_critical_violation = True',
    'Context Review',
    'Do not auto-penalize; require manager + HR joint review',
    'High',
    'All employees',
  ],
  [
    'NORM-C03',
    'Composite Risk',
    'Bench + Low score = talent risk',
    'assignment_type = Bench AND score < 3.0',
    'Talent Risk',
    'Priority reassignment or exit discussion with HR',
    'High',
    'All employees',
  ],
  [
    'NORM-C04',
    'Composite Risk',
    'Multi-period downward performance trend',
    'score decline for 3+ consecutive months',
    'Downward Trend',
    'Mandatory performance improvement plan; notify BOD if senior level',
    'High',
    'Senior employees (L5+)',
  ],
  [
    'NORM-G01',
    'Report Guard',
    'Do not conclude final performance without reviewer sign-off',
    'reviewer_id must be non-null AND report_period must be closed',
    'Guard',
    'Block report section; flag as pending review',
    'High',
    'All report outputs',
  ],
  [
    'NORM-G02',
    'Report Guard',
    'Salary data — restricted access',
    'salary_band exposed only to authorized_roles',
    'Access Control',
    'Mask salary_band if user role != HR or BOD',
    'Critical',
    'Salary data',
  ],
  [
    'NORM-G03',
    'Report Guard',
    'Avoid biased language in attitude assessment',
    'qualitative fields must not contain direct judgment of character',
    'Language Guard',
    'Flag for L&D/HR editorial review before report distribution',
    'Medium',
    'Qualitative feedback fields',
  ],
] as const;

/** DS-04b · Violation Type Reference — the 26 documented violation types. */
const VERBAL = 'Verbal warning';
const WRITTEN = 'Written warning';
const FINAL = 'Final warning / PIP';
export const VIOLATION_TYPES = [
  ['Attendance', 'ATT-01', 'Late arrival (>15 min)', 'Low', VERBAL],
  ['Attendance', 'ATT-02', 'Unexcused absence', 'Low', VERBAL],
  ['Attendance', 'ATT-03', 'Early departure without approval', 'Low', VERBAL],
  ['Attendance', 'ATT-04', 'No check-in / check-out recorded', 'Low', VERBAL],
  ['Attendance', 'ATT-05', 'Repeated tardiness (3+ times/month)', 'Low', VERBAL],
  ['Attitude', 'ATT-A01', 'Disrespectful behavior toward colleague', 'Medium', WRITTEN],
  ['Attitude', 'ATT-A02', 'Disrespectful behavior toward manager', 'Medium', WRITTEN],
  ['Attitude', 'ATT-A03', 'Unprofessional communication (chat/email)', 'Medium', WRITTEN],
  ['Attitude', 'ATT-A04', 'Negative attitude affecting team morale', 'Medium', WRITTEN],
  ['Attitude', 'ATT-A05', 'Refusal to follow reasonable instructions', 'Medium', WRITTEN],
  ['Attitude', 'ATT-A06', 'Conflict / argument in workplace', 'Medium', WRITTEN],
  ['Performance', 'PERF-01', 'Missed deadline without notice', 'Medium', WRITTEN],
  ['Performance', 'PERF-02', 'Repeated low-quality output', 'Medium', WRITTEN],
  ['Performance', 'PERF-03', 'Failure to meet KPI target 2 cycles', 'Medium', WRITTEN],
  ['Performance', 'PERF-04', 'Incomplete task delivery', 'Medium', WRITTEN],
  ['Policy', 'POL-01', 'Unauthorized use of company equipment', 'Medium', WRITTEN],
  ['Policy', 'POL-02', 'Data security policy breach', 'Medium', WRITTEN],
  ['Policy', 'POL-03', 'Sharing confidential info externally', 'Medium', WRITTEN],
  ['Policy', 'POL-04', 'Failure to complete mandatory training', 'Medium', WRITTEN],
  ['Policy', 'POL-05', 'Violation of dress code policy', 'Medium', WRITTEN],
  ['Policy', 'POL-06', 'Personal use of company resources', 'Medium', WRITTEN],
  ['Conduct', 'CON-01', 'Harassment or inappropriate language', 'High', FINAL],
  ['Conduct', 'CON-02', 'Dishonesty / falsifying records', 'High', FINAL],
  ['Conduct', 'CON-03', 'Conflict of interest not disclosed', 'High', FINAL],
  ['Conduct', 'CON-04', 'Working for competitor without disclosure', 'High', FINAL],
  ['Conduct', 'CON-05', 'Theft or misappropriation', 'High', FINAL],
] as const;

/** REF · Project Master — accounts and their projects (used to decode + to allocate). */
export const PROJECTS = [
  ['ACC-A', 'Account Alpha', 'ACC-A-P01', 'Project ACC-A-P01'],
  ['ACC-A', 'Account Alpha', 'ACC-A-P02', 'Project ACC-A-P02'],
  ['ACC-A', 'Account Alpha', 'ACC-A-P03', 'Project ACC-A-P03'],
  ['ACC-A', 'Account Alpha', 'ACC-A-P04', 'Project ACC-A-P04'],
  ['ACC-B', 'Account Beta', 'ACC-B-P01', 'Project ACC-B-P01'],
  ['ACC-B', 'Account Beta', 'ACC-B-P02', 'Project ACC-B-P02'],
  ['ACC-B', 'Account Beta', 'ACC-B-P03', 'Project ACC-B-P03'],
  ['ACC-C', 'Account Gamma', 'ACC-C-P01', 'Project ACC-C-P01'],
  ['ACC-C', 'Account Gamma', 'ACC-C-P02', 'Project ACC-C-P02'],
  ['ACC-C', 'Account Gamma', 'ACC-C-P03', 'Project ACC-C-P03'],
  ['ACC-D', 'Account Delta', 'ACC-D-P01', 'Project ACC-D-P01'],
  ['ACC-D', 'Account Delta', 'ACC-D-P02', 'Project ACC-D-P02'],
  ['ACC-E', 'Account Epsilon', 'ACC-E-P01', 'Project ACC-E-P01'],
  ['ACC-E', 'Account Epsilon', 'ACC-E-P02', 'Project ACC-E-P02'],
  ['INTERNAL', 'Internal', 'INT-P00', 'Bench / Internal'],
] as const;
